### ISSUE TITLE
Doesn't work, I'm afraid.

### ISSUE THREAD

**Issue by g1ps** [wasilak/ansible-lint-junit#1]
```
-sh-4.2$ ansible-lint-junit ./linttest.txt -o ansible-lint.xml
Traceback (most recent call last):
  File "/usr/bin/ansible-lint-junit", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/bootstrap/bootstrap.py", line 57, in main

    "filename": line_match.group(1),
AttributeError: 'NoneType' object has no attribute 'group'
```

linttest.txt contains ansible-lint output obtained as described.

**Comment by CrazyLionHeart** [comment]
Remove versbosity level from ansible-lint config.

**Comment by g1ps** [comment]
I tried that. It makes no difference. `-q` doesn't help, either. Any playbook generates a line in the output file like
````
Examining <playbook>.yml of type playbook
````
and it chokes on that. It only works if the file is empty and since that is never normally the case, it seems broken.

Thanks.

**Comment by g1ps** [comment]
It figures....shortly after replying I relaised that `.ansible-lint` is overriding the command line parameter. Setting 
````
verbosity: 0
````
has resolved that. It appears that you can increase verbosity on the command line but not reduce it.
