### ISSUE TITLE
Fails to output to xml file

### ISSUE THREAD

**Issue by sorhtyre** [wasilak/ansible-lint-junit#11]
```
$ ansible-lint --version
ansible-lint 5.0.7 using ansible 2.9.20
$ cat .ansible-lint
verbosity: 0
$ ansible-lint -q -p . | ansible-lint-junit -o ansible-lint.xml
WARNING  Listing 16 violation(s) that are fatal
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint-junit", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/bootstrap/bootstrap.py", line 62, in main
    "filename": line_match.group(1),
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by sorhtyre** [comment]
I'll have to do some more testing, but it seems to be an issue with ansible-lint's output. Not sure at what version it changed, but modifying the regular expression on line 49 of bootstrap.py corrects the issue as far as ansible-lint v5.0.7 is concerned.
From:
`line_regex = re.compile('^(.*?):(\\d+?):\\s\\[(.*)\\]\\s(.*)$')`
To:
`line_regex = re.compile('^(.*?):(\d+?):\s(.*)\s(.*)$')`

**Comment by wasilak** [comment]
Hi @sorhtyre I've managed to push new version with changes addressing your issue, please check version https://github.com/wasilak/ansible-lint-junit/releases/tag/0.16 plus updated README.

Cheers!
