### ISSUE TITLE
No module named 'version' error in 0.17.5

### ISSUE THREAD

**Issue by thedoc31** [wasilak/ansible-lint-junit#18]
ansible-lint-junit was working for us until today. It appears the commit [b5b5435ef9704085f2ab820560ec1223949af43e](https://github.com/wasilak/ansible-lint-junit/commit/b5b5435ef9704085f2ab820560ec1223949af43e) may have broken it.

```
Traceback (most recent call last):
  File "/home/circleci/.local/bin/ansible-lint-junit", line 5, in <module>
    from ansible_lint_junit.main import main
  File "/home/circleci/.local/lib/python3.6/site-packages/ansible_lint_junit/main.py", line 7, in <module>
    from  version import __version__
ModuleNotFoundError: No module named 'version'
```

**Comment by wasilak** [comment]
Hey, try with version 0.17.6, I've pushed fix

**Comment by thedoc31** [comment]
Looks better, thank you!
