### ISSUE TITLE
Bamboo's JUnit Parser ignores result file with 0 tests

### ISSUE THREAD

**Issue by Montellese** [wasilak/ansible-lint-junit#19]
Thanks for this nice tool.

I'm using it with Bamboo as follows:
```bash
ansible-lint -p --nocolor 2> /dev/null | \
ansible-lint-junit -o ansible-lint-junit.xml
```

If there are no errors from `ansible-lint` the dummy `ansible-lint-junit.xml` file with `0` tests and `0` errors/failures is generated, but Bamboo's JUnit Parser seems to ignore files with `0` tests.

Running the following script, i.e. replacing the `0` tests with `1` dummy testcase, solves this issue:
```bash
ansible-lint -p --nocolor 2> /dev/null | \
ansible-lint-junit -v | \
sed 's/<testsuite errors="0" failures="0" tests="0" time="0"\/>/<testsuite errors="0" failures="0" tests="1" time="0"><testcase name="ansible-lint" status="run" time="0" errors="0"><\/testcase><\/testsuite>/g' > ansible-lint-junit.xml
```

**Comment by wasilak** [comment]
Hey @Montellese , check out commit f6051bd - I've added optional argument handling your case :)

```python
parser.add_argument("-d", "--dummy-test", dest="dummy", action="store_true", help="Adds single (1) dummy test if there were 0 tests and/or 0 errors", default=False)
```

This feature will be in version `0.17.8`, should be already available via `pip` 👍
