### ISSUE TITLE
Allow pipe as yamllint-junit does

### ISSUE THREAD

**Issue by Zauxst** [wasilak/ansible-lint-junit#7]
Hi for CI/CD tools it would be valuable if we can pipe the output in the same manner that we can do with yamllint and yamllint-junit.
Example:
```
yamllint -f parsable | yamllint-junit -o reports/junit-yaml-lint.xml
```

**Comment by wasilak** [comment]
Hi

Check version 0.12. You can use it now like this: `cat output.txt | ansible-lint-junit -o ansible-lint.xml` or `ansible-lint playbook.yml -p | ansible-lint-junit -o ansible-lint.xml`.

**Comment by Zauxst** [comment]
Thanks, I've tested it out it works as described.
